# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'E-Commerce' do
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire','~> 4.8.1'
  pod 'AlamofireImage','~> 3.5.0'
  pod 'SVPullToRefresh'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'SwiftyJSON'
end

  # Pods for E-Commerce

  target 'E-CommerceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-CommerceUITests' do
    # Pods for testing
  end

